version: '3.5'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
#      - API_URL=http://localhost:8000/api
      - API_URL=http://13.59.57.0/api
    volumes:
      - static:/usr/src/app/mini_chat/root/static
  db:
    image: postgres:12-alpine
    volumes:
     - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=mini_chat_dev
      - POSTGRES_PASSWORD=mini_chat_passwd
      - POSTGRES_DB=mini_chat_dev_db
      - TZ=America/Bogota
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    command: npm start --prefix /usr/src/app/frontend/mini_chat
    # volumes:
    #   - ./web_client:/usr/src/app/
    ports:
      - 3000:3000
    stdin_open: true
    depends_on:
      - backend
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static:/usr/src/app/mini_chat/root/static
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend

volumes:
  postgres_data:
  static:
