version: '3.5'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=mini_chat_dev
      - POSTGRES_PASSWORD=mini_chat_passwd
      - POSTGRES_DB=mini_chat_dev_db
      - TZ=America/Bogota

