# Generated by Django 3.0.5 on 2020-11-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_sign_in',
            field=models.DateField(null=True),
        ),
    ]
