# Generated by Django 3.0.5 on 2020-11-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_message_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media',
            field=models.BooleanField(default=False),
        ),
    ]
