# Generated by Django 3.0.5 on 2020-11-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201129_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='mediaSrc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
