# Generated by Django 3.0.5 on 2020-11-29 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201129_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='mediaSrc',
            new_name='media_src',
        ),
    ]
